# Site settings
title: CommonKarma.org
whatif_email: whatif@commonkarma.org
description: > # this means to ignore newlines until "baseurl:"
  What if there were consequences to pushing trash on the web?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://CommonKarma.org" # the base hostname & protocol for your site
twitter_username: CommonKarma
github_username:  CommonKarma

# Build settings
markdown: kramdown


kramdown:
  parse_block_html: true

# these are copied from https://github.com/bookfellas/bookfellas.github.io 
# not sure if correct or needed.
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"